FROM ubuntu:16.04
MAINTAINER Vishal Sharma "vish.sharma0203@gmail.com"

RUN apt-get update && apt-get install -y nodejs
RUN mv /usr/bin/nodejs /usr/bin/node

WORKDIR /var/www/collegemate
COPY . /var/www/collegemate

RUN mkdir -p /var/www/collegemate/creds
COPY ./creds/* /var/www/collegemate/creds/

EXPOSE 6001

CMD ["/usr/bin/node", "pubsub-server.js"]
